import { posterOverrides } from './posterOverrides.generated.js'

const accents = ['red', 'blue', 'gold', 'green', 'violet']
const originLabels = {
  dominicanMade: 'Hecha en RD por dominicanos',
  foreignInDr: 'Hecha en RD por no dominicanos',
  outsideScope: 'Fuera del filtro principal',
}

const foreignInDominicanRepublicTitles = new Set([
  'Excursión de José de Diego en Santo Domingo',
  'Marcha del trabajo',
  'El clan de los inmorales',
  'Guaguasi',
  'Azúcar amarga',
  'Luis Vargas: Santo Domingo Blues',
  'La fiesta del chivo',
  'La Soga',
  'Morir soñando',
  'El rey de La Habana',
  'Todos los hombres son iguales',
  'Ovni',
  'Cinderelo',
  'La estrategia del mero',
])

const outsideScopeTitles = new Set([
  'In the Time of the Butterflies',
  'Washington Heights',
  'La ternura',
])

const rawFilms = [
  {
    year: 1915,
    title: 'Excursión de José de Diego en Santo Domingo',
    director: 'Rafael Colorado',
    type: 'Documental',
    note: 'Primera película hecha en República Dominicana por un extranjero.',
  },
  {
    year: 1923,
    title: 'La Leyenda de Nuestra Señora de Altagracia',
    director: 'Francisco Arturo Palau',
    type: 'Drama',
    note: 'Primera película de ficción del cine dominicano.',
  },
  {
    year: 1923,
    title: 'La República Dominicana',
    director: 'Francisco Arturo Palau',
    type: 'Documental',
    note: 'Retrato documental de la vida dominicana de la época.',
  },
  {
    year: 1924,
    title: 'Las emboscadas de Cupido',
    director: 'Francisco Arturo Palau',
    type: 'Comedia',
    note: 'Comedia muda de la etapa inicial del cine nacional.',
  },
  {
    year: 1947,
    title: 'Marcha del trabajo',
    director: 'Rudy Unger',
    type: 'Propaganda',
    note: 'Obra de la etapa fílmica durante la dictadura de Trujillo.',
  },
  {
    year: 1948,
    title: 'Palmas dominicanas',
    director: 'No registrado',
    type: 'Documental',
    note: 'Registro temprano incluido en la filmografía dominicana.',
  },
  {
    year: 1958,
    title: 'Ganadería: Riqueza nacional',
    director: 'Manuel Báez',
    type: 'Documental',
    note: 'Primer documental dominicano en 35mm y a color.',
  },
  {
    year: 1961,
    title: 'La Gesta Libertadora del 30 de Mayo',
    director: 'Hugo Mateo',
    type: 'Documental',
    note: 'Documental histórico sobre el ajusticiamiento de Trujillo.',
  },
  {
    year: 1963,
    title: 'La Silla',
    director: 'Franklin Dominguez',
    type: 'Drama',
    note: 'Primera producción dominicana después de la caída de Trujillo.',
  },
  {
    year: 1968,
    title: 'El esfuerzo de un pueblo',
    director: 'Eduardo Palmer y Max Pou',
    type: 'Documental',
    note: 'Documental de reconstrucción y memoria nacional.',
  },
  {
    year: 1969,
    title: 'Carnaval',
    director: 'Ricardo Thormann y Max Pou',
    type: 'Documental',
    note: 'Film promocional sobre cultura y turismo dominicano.',
  },
  {
    year: 1970,
    title: 'Santo Domingo: Cuna de América',
    director: 'Max Pou',
    type: 'Documental',
    note: 'Documental histórico y turístico sobre Santo Domingo.',
  },
  {
    year: 1973,
    title: 'La serpiente de la luna de los piratas',
    director: 'Jean-Louis Jorge',
    type: 'Drama',
    note: 'Obra de culto premiada en el Festival de Toulon.',
  },
  {
    year: 1975,
    title: 'El clan de los inmorales',
    director: 'José Gutiérrez Maesso',
    type: 'Drama',
    note: 'Producción vinculada a República Dominicana.',
  },
  {
    year: 1976,
    title: 'Lengua azul',
    director: 'Max Pou',
    type: 'Documental',
    note: 'Documental de la filmografía dominicana de los setenta.',
  },
  {
    year: 1976,
    title: 'Los dueños del sol',
    director: 'No registrado',
    type: 'Documental',
    note: 'Tambien conocida como Fondo negro.',
  },
  {
    year: 1977,
    title: 'Crisis',
    director: 'Onofre de la Rosa',
    type: 'Documental',
    note: 'Sobre la agresión económica y militar contra la UASD.',
  },
  {
    year: 1978,
    title: 'Siete dias con el pueblo',
    director: 'Jimmy Sierra',
    type: 'Documental',
    note: 'Sobre el festival musical celebrado en 1974.',
  },
  {
    year: 1978,
    title: 'Rumbo al poder',
    director: 'José Bujosa',
    type: 'Documental',
    note: 'Sobre las elecciones dominicanas de 1978.',
  },
  {
    year: 1981,
    title: 'Carnival y mascas',
    director: 'Pedro Guzman Cordero',
    type: 'Documental',
    note: 'Documental sobre carnaval y folklore dominicano.',
  },
  {
    year: 1981,
    title: 'El mundo mágico de Gilberto Hernández Ortega',
    director: 'Agliberto Melendez',
    type: 'Documental',
    note: 'Retrato del artista Gilberto Hernández Ortega.',
  },
  {
    year: 1981,
    title: 'Lumiantena',
    director: 'Máximo Rodríguez y Martín López',
    type: 'Experimental',
    note: 'Proyecto universitario de la UASD.',
  },
  {
    year: 1983,
    title: 'Guaguasi',
    director: 'Jorge Ulla',
    type: 'Drama',
    note: 'Drama filmado en República Dominicana.',
  },
  {
    year: 1983,
    title: 'El valle de San Juan',
    director: 'Claudio Chea',
    type: 'Documental',
    note: 'Documental sobre preservación ecológica.',
  },
  {
    year: 1983,
    title: 'El paseo de la Virgen',
    director: 'No registrado',
    type: 'Documental',
    note: 'Sobre tradiciones de Palmar de Ocoa.',
  },
  {
    year: 1985,
    title: 'Tras las huellas de Palau',
    director: 'René Fortunato',
    type: 'Documental',
    note: 'Historia del primer cineasta dominicano, Francisco Palau.',
  },
  {
    year: 1985,
    title: 'A golpe de heroísmo',
    director: 'Tommy Garcia',
    type: 'Documental',
    note: 'Sobre la Revolución de Abril.',
  },
  {
    year: 1985,
    title: 'Camino al Pico Duarte',
    director: 'Claudio Chea',
    type: 'Documental',
    note: 'Sobre deforestación y territorio.',
  },
  {
    year: 1985,
    title: 'La ruta de la libertad',
    director: 'Pericles Mejía y José Luis Sáez',
    type: 'Documental',
    note: 'Sobre Máximo Gómez.',
  },
  {
    year: 1987,
    title: 'Algo en comun',
    director: 'Jean-Louis Jorge',
    type: 'Documental',
    note: 'Sobre el compositor Julio Alberto Hernández.',
  },
  {
    year: 1988,
    title: 'Abril: La trinchera del honor',
    director: 'René Fortunato',
    type: 'Documental',
    note: 'Premiada como documental caribeño en San Juan.',
  },
  {
    year: 1988,
    title: 'Un pasaje de Ida',
    director: 'Agliberto Melendez',
    type: 'Drama',
    note: 'Largometraje clave sobre migración dominicana.',
  },
  {
    year: 1988,
    title: 'Trafico de ninos',
    director: 'Alfonso Rodríguez',
    type: 'TV movie',
    note: 'Drama televisivo dominicano.',
  },
  {
    year: 1990,
    title: 'Caribe',
    director: 'René Fortunato',
    type: 'Documental',
    note: 'Documental sobre salsa.',
  },
  {
    year: 1991,
    title: 'Trujillo: El Poder del Jefe',
    director: 'René Fortunato',
    type: 'Documental',
    note: 'Primera parte de la trilogia documental sobre Trujillo.',
  },
  {
    year: 1994,
    title: 'Trujillo: El Poder del Jefe II',
    director: 'René Fortunato',
    type: 'Documental',
    note: 'Segunda parte de la trilogia.',
  },
  {
    year: 1995,
    title: 'Nueba Yol: Por Fin Llego Balbuena',
    director: 'Ángel Muñiz',
    type: 'Comedia',
    note: 'Hito popular de la comedia dominicana.',
  },
  {
    year: 1996,
    title: 'Azúcar amarga',
    director: 'Leon Ichaso',
    type: 'Drama romántico',
    note: 'Coproducción dominico-estadounidense filmada en Santo Domingo.',
  },
  {
    year: 1996,
    title: 'Cuatro hombres y un ataud',
    director: 'Pericles Mejía',
    type: 'Comedia',
    note: 'Comedia dominicana de los noventa.',
  },
  {
    year: 1996,
    title: 'Para Vivir o Morir',
    director: 'Radel Villalona y José Romay',
    type: 'Drama',
    note: 'Drama dominicano estrenado en la década de 1990.',
  },
  {
    year: 1997,
    title: 'Buscando Un Sueno',
    director: 'Joseph Medina, Jaime Piña y David Castillo',
    type: 'Drama',
    note: 'Drama con guion de Freddy Vargas y Joseph Medina.',
  },
  {
    year: 1997,
    title: 'Nueba Yol 3: Bajo la Nueva Ley',
    director: 'Ángel Muñiz',
    type: 'Comedia',
    note: 'Continuacion de la saga de Balbuena.',
  },
  {
    year: 1998,
    title: 'Balaguer: La Herencia del Tirano',
    director: 'René Fortunato',
    type: 'Documental',
    note: 'Documental histórico sobre Joaquín Balaguer.',
  },
  {
    year: 2000,
    title: 'El Circulo Vicioso',
    director: 'Nelson Peña',
    type: 'Acción',
    note: 'Acción dominicana de inicios de siglo.',
  },
  {
    year: 2001,
    title: 'In the Time of the Butterflies',
    director: 'Mariano Barroso',
    type: 'Drama histórico',
    note: 'Sobre las hermanas Mirabal.',
  },
  {
    year: 2002,
    title: 'Washington Heights',
    director: 'Alfredo De Villa',
    type: 'Drama',
    note: 'Historia dominico-estadounidense premiada en festivales.',
  },
  {
    year: 2003,
    title: 'Exito por intercambio',
    director: 'Miguel Vásquez',
    type: 'Comedia',
    note: 'Producción dominicana de 2003.',
  },
  {
    year: 2003,
    title: 'Luis Vargas: Santo Domingo Blues',
    director: 'Alex Wolfe',
    type: 'Documental',
    note: 'Sobre la bachata y la carrera de Luis Vargas.',
  },
  {
    year: 2003,
    title: 'Pasaporte Rojo',
    director: 'Albert Xavier',
    type: 'Drama',
    note: 'Drama basado en una historia de Freddy Vargas.',
  },
  {
    year: 2003,
    title: 'Perico Ripiao',
    director: 'Ángel Muñiz',
    type: 'Comedia',
    photo:
      'https://media.themoviedb.org/t/p/w780/P8e6j10np0UVb0nZB960dPAQxW.jpg',
    note: 'Comedia popular sobre tres fugitivos y musica tipica.',
  },
  {
    year: 2003,
    title: 'Balaguer: La violencia del poder',
    director: 'René Fortunato',
    type: 'Documental',
    note: 'Documental sobre Joaquín Balaguer.',
  },
  {
    year: 2004,
    title: 'La carcel de la Victoria: El cuarto hombre',
    director: 'José Enrique Pintor',
    type: 'Drama',
    note: 'Drama dominicano ambientado en el sistema penitenciario.',
  },
  {
    year: 2004,
    title: 'Negocios son negocios',
    director: 'Jorge De Bernardi',
    type: 'Comedia',
    note: 'Comedia dominicana.',
  },
  {
    year: 2004,
    title: 'La Ruta',
    director: 'David Cavada Oruna',
    type: 'Corto',
    note: 'Cortometraje incluido en la filmografía nacional.',
  },
  {
    year: 2004,
    title: 'Soy: Johnny Ventura',
    director: 'Guillermo Cordero',
    type: 'Documental',
    note: 'Documental sobre Johnny Ventura.',
  },
  {
    year: 2005,
    title: 'Andrea: La Venganza del Espíritu',
    director: 'Rogert Bencosme',
    type: 'Terror',
    note: 'Terror dominicano de amplia circulación popular.',
  },
  {
    year: 2005,
    title: 'La fiesta del chivo',
    director: 'Luis Llosa',
    type: 'Drama histórico',
    note: 'Adaptación sobre la dictadura de Trujillo.',
  },
  {
    year: 2005,
    title: 'Los locos tambien piensan',
    director: 'Humberto Castellanos',
    type: 'Acción',
    note: 'Acción dominicana.',
  },
  {
    year: 2005,
    title: 'Un rollo en la arena',
    director: 'Félix Manuel Lora Robles',
    type: 'Documental',
    note: 'Documental sobre cine dominicano.',
  },
  {
    year: 2005,
    title: 'La maldicion del padre Cardona',
    director: 'Félix Germán',
    type: 'Comedia romántica',
    note: 'Comedia romántica con Zoe Saldaña.',
  },
  {
    year: 2006,
    title: 'Un macho de mujer',
    director: 'Alfonso Rodríguez',
    type: 'Comedia',
    note: 'Comedia popular dominicana.',
  },
  {
    year: 2006,
    title: 'Patricia: el regreso del sueño',
    director: 'René Fortunato',
    type: 'Drama',
    note: 'Drama dominicano.',
  },
  {
    year: 2006,
    title: 'Lilís',
    director: 'Jimmy Sierra',
    type: 'Drama histórico',
    note: 'Sobre la vida de Ulises Heureaux.',
  },
  {
    year: 2006,
    title: 'El Sistema',
    director: 'Humberto Espinal',
    type: 'Acción',
    note: 'Acción dominicana.',
  },
  {
    year: 2006,
    title: 'Viajeros',
    director: 'Carlos Bido',
    type: 'Drama',
    note: 'Sobre migración ilegal.',
  },
  {
    year: 2007,
    title: 'Mi novia está de madre',
    director: 'Archie Lopez',
    type: 'Comedia',
    note: 'Comedia popular de Archie Lopez.',
  },
  {
    year: 2007,
    title: 'Sanky Panky',
    director: 'José Enrique Pintor',
    type: 'Comedia',
    note: 'Comedia turística y popular dominicana.',
  },
  {
    year: 2007,
    title: 'Operación Patakón',
    director: 'Tito Nekerman',
    type: 'Comedia',
    note: 'Comedia dominicana.',
  },
  {
    year: 2007,
    title: 'Yuniol',
    director: 'Alfonso Rodríguez',
    type: 'Drama',
    note: 'Drama social dominicano.',
  },
  {
    year: 2008,
    title: 'Al fin y al cabo',
    director: 'Alfonso Rodríguez',
    type: 'Comedia',
    note: 'Comedia dominicana.',
  },
  {
    year: 2008,
    title: 'El caballero de la medianoche',
    director: 'Jimmy Sierra',
    type: 'Thriller',
    note: 'Thriller dominicano.',
  },
  {
    year: 2008,
    title: 'Enigma',
    director: 'Robert Cornelio',
    type: 'Suspenso / terror',
    note: 'Suspenso y terror dominicano.',
  },
  {
    year: 2008,
    title: 'Excexos',
    director: 'José María Cabral',
    type: 'Drama',
    note: 'Drama temprano de José María Cabral.',
  },
  {
    year: 2008,
    title: 'Ladrones a domicilio',
    director: 'Ángel Muñiz',
    type: 'Aventura',
    note: 'Aventura dominicana.',
  },
  {
    year: 2008,
    title: 'Playball',
    director: 'Alfonso Rodríguez',
    type: 'Drama deportivo',
    note: 'Sobre jugadores dominicanos de béisbol.',
  },
  {
    year: 2008,
    title: 'Santi Clo... La vaina de la Navidad',
    director: 'José Enrique Pintor',
    type: 'Comedia',
    note: 'Comedia navideña dominicana.',
  },
  {
    year: 2009,
    title: 'Cristiano de la Secreta',
    director: 'Archie Lopez',
    type: 'Comedia',
    note: 'Comedia dominicana con Raymond Pozo.',
  },
  {
    year: 2009,
    title: 'La Soga',
    director: 'Josh Crook',
    type: 'Acción',
    note: 'Acción sobre corrupción y justicia.',
  },
  {
    year: 2009,
    title: 'Bosch: Presidente en la frontera imperial',
    director: 'René Fortunato',
    type: 'Documental',
    note: 'Documental sobre Juan Bosch.',
  },
  {
    year: 2009,
    title: 'Mega Diva',
    director: 'Roberto Ángel Salcedo',
    type: 'Comedia',
    note: 'Comedia dominicana.',
  },
  {
    year: 2010,
    title: 'Trópico de sangre',
    director: 'Juan Delancer',
    type: 'Drama histórico',
    note: 'Sobre las hermanas Mirabal.',
  },
  {
    year: 2011,
    title: '3 al rescate',
    director: 'Jorge Morillo y Luis Morillo',
    type: 'Animacion',
    note: 'Primera película animada hecha por completo en República Dominicana.',
  },
  {
    year: 2011,
    title: 'La hija natural',
    director: 'Leticia Tonos',
    type: 'Drama',
    note: 'Drama de Leticia Tonos.',
  },
  {
    year: 2012,
    title: 'Jaque Mate',
    director: 'José María Cabral',
    type: 'Drama / thriller',
    note: 'Thriller dominicano.',
  },
  {
    year: 2012,
    title: 'Feo de dia, lindo de noche',
    director: 'Alfonso Rodríguez',
    type: 'Comedia',
    note: 'Comedia fantástica dominicana.',
  },
  {
    year: 2012,
    title: 'Lotoman 2.0',
    director: 'Archie Lopez',
    type: 'Comedia',
    note: 'Secuela de la saga Lotoman.',
  },
  {
    year: 2012,
    title: 'El hoyo del diablo',
    director: 'Francis Disla',
    type: 'Terror',
    note: 'Terror dominicano.',
  },
  {
    year: 2012,
    title: 'El Rey de Najayo',
    director: 'Fernando Báez Mella',
    type: 'Drama',
    note: 'Inspirada en la figura de un narcotraficante.',
  },
  {
    year: 2012,
    title: 'La lucha de Ana',
    director: 'Bladimir Abud',
    type: 'Drama',
    note: 'Drama dominicano protagonizado por Cheddy García.',
  },
  {
    year: 2013,
    title: 'Cristo Rey',
    director: 'Leticia Tonos',
    type: 'Drama',
    note: 'Drama urbano dominicano.',
  },
  {
    year: 2013,
    title: 'Profe por accidente',
    director: 'Roberto Ángel Salcedo',
    type: 'Comedia',
    note: 'Comedia escolar dominicana.',
  },
  {
    year: 2013,
    title: 'A ritmo de fe',
    director: 'José Gómez',
    type: 'Drama',
    note: 'Drama sobre danza y fe.',
  },
  {
    year: 2013,
    title: 'Los super',
    director: 'Bladimir Abud',
    type: 'Comedia',
    note: 'Comedia dominicana.',
  },
  {
    year: 2013,
    title: 'Arroba',
    director: 'José María Cabral',
    type: 'Comedia',
    note: 'Comedia dominicana.',
  },
  {
    year: 2013,
    title: 'El teniente Amado',
    director: 'Félix Limardo',
    type: 'Drama histórico',
    note: 'Sobre Amado Garcia Guerrero.',
  },
  {
    year: 2013,
    title: 'Biodegradable',
    director: 'Juan Basanta',
    type: 'Drama / ciencia ficción',
    note: 'Drama con elementos de ciencia ficción.',
  },
  {
    year: 2014,
    title: 'Dólares de arena',
    director: 'Laura Amelia Guzman e Israel Cardenas',
    type: 'Drama',
    note: 'Drama ambientado en Las Terrenas.',
  },
  {
    year: 2014,
    title: 'Vamos de robo',
    director: 'Roberto Ángel Salcedo',
    type: 'Comedia',
    note: 'Comedia dominicana.',
  },
  {
    year: 2014,
    title: 'Duarte, traición y gloria',
    director: 'Leo Silverio',
    type: 'Drama histórico',
    note: 'Sobre Juan Pablo Duarte.',
  },
  {
    year: 2014,
    title: 'Locas y atrapadas',
    director: 'Alfonso Rodríguez',
    type: 'Drama',
    note: 'Drama coral dominicano.',
  },
  {
    year: 2014,
    title: 'De pez en cuando',
    director: 'Francisco Valdez',
    type: 'Comedia',
    note: 'Comedia dominicana.',
  },
  {
    year: 2014,
    title: 'Lotoman 003',
    director: 'Archie Lopez',
    type: 'Comedia',
    note: 'Entrega de la saga Lotoman.',
  },
  {
    year: 2014,
    title: 'Al sur de la inocencia',
    director: 'Héctor Manuel Valdez',
    type: 'Drama',
    note: 'Drama dominicano.',
  },
  {
    year: 2014,
    title: 'La extraña',
    director: 'César Rodríguez',
    type: 'Drama',
    note: 'Remake dominicano de L étrangère.',
  },
  {
    year: 2014,
    title: 'Despertar',
    director: 'José María Cabral',
    type: 'Thriller psicológico',
    note: 'Thriller psicológico dominicano.',
  },
  {
    year: 2014,
    title: 'Código paz',
    director: 'Pedro Urrutia',
    type: 'Acción',
    note: 'Acción dominicana.',
  },
  {
    year: 2014,
    title: 'María Montez',
    director: 'Vicente Peñarrocha',
    type: 'Biografía',
    note: 'Drama biográfico sobre María Montez.',
  },
  {
    year: 2015,
    title: 'El rey de La Habana',
    director: 'Agustí Villaronga',
    type: 'Drama',
    note: 'Coproducción hispano-dominicana.',
  },
  {
    year: 2015,
    title: 'Los Paracaidistas',
    director: 'Archie Lopez',
    type: 'Comedia',
    note: 'Comedia dominicana.',
  },
  {
    year: 2015,
    title: 'Detective Willy',
    director: 'José María Cabral',
    type: 'Comedia de aventura',
    note: 'Comedia de aventura dominicana.',
  },
  {
    year: 2015,
    title: "Pa'l Campamento",
    director: 'Roberto Ángel Salcedo',
    type: 'Comedia',
    note: 'Comedia dominicana.',
  },
  {
    year: 2015,
    title: 'Una breve historia de amor',
    director: 'Alan Nadal Piantini',
    type: 'Comedia romántica',
    note: 'Comedia romántica dominicana.',
  },
  {
    year: 2015,
    title: 'Bestia de Cardo',
    director: 'Virginia Sánchez Navarro',
    type: 'Drama',
    note: 'Drama dominicano.',
  },
  {
    year: 2015,
    title: 'Morir soñando',
    director: 'Josh Crook',
    type: 'Drama',
    note: 'Drama dominicano.',
  },
  {
    year: 2015,
    title: 'La Gunguna',
    director: 'Ernesto Alemany',
    type: 'Comedia criminal',
    photo:
      'https://media.themoviedb.org/t/p/w780/sTYpgsdIT98GHOqsV4fyxfBvudk.jpg',
    note: 'Una pistola calibre .22 conecta historias del bajo mundo caribeño.',
  },
  {
    year: 2015,
    title: 'Tú y yo',
    director: 'Natalia Cabral y Oriol Estrada',
    type: 'Documental',
    note: 'Sobre la relacion entre una empleada domestica y su empleadora.',
  },
  {
    year: 2015,
    title: "Pueto' pa' mi",
    director: 'Iván Herrera',
    type: 'Drama',
    note: 'Drama musical urbano dominicano.',
  },
  {
    year: 2015,
    title: 'Algún lugar',
    director: 'Guillermo Zouain',
    type: 'Drama',
    note: 'Road movie juvenil dominicana.',
  },
  {
    year: 2015,
    title: 'Todo incluido',
    director: 'Roberto Ángel Salcedo',
    type: 'Comedia',
    note: 'Comedia dominicana.',
  },
  {
    year: 2015,
    title: 'Tubérculo Gourmet',
    director: 'Archie Lopez',
    type: 'Comedia',
    note: 'Comedia popular dominicana.',
  },
  {
    year: 2015,
    title: 'Del color de la noche',
    director: 'Agliberto Melendez',
    type: 'Drama histórico',
    note: 'Sobre José Francisco Pena Gómez.',
  },
  {
    year: 2016,
    title: 'Todos los hombres son iguales',
    director: 'Manuel Gómez Pereira',
    type: 'Comedia',
    note: 'Comedia dominicana basada en la película española homónima.',
  },
  {
    year: 2016,
    title: 'Ovni',
    director: 'Raúl Marchand Sánchez',
    type: 'Ciencia ficción / comedia',
    note: 'Comedia de ciencia ficción dominicana.',
  },
  {
    year: 2016,
    title: 'Jeffrey',
    director: 'Yanillys Pérez',
    type: 'Documental',
    note: 'Sobre un joven que busca convertirse en cantante urbano.',
  },
  {
    year: 2016,
    title: 'Flor de azucar',
    director: 'Fernando Báez Mella',
    type: 'Aventura / drama',
    note: 'Drama rural dominicano.',
  },
  {
    year: 2016,
    title: 'Sitio de sitios',
    director: 'Natalia Cabral y Oriol Estrada',
    type: 'Documental',
    note: 'Sobre la economía turística dominicana.',
  },
  {
    year: 2016,
    title: 'A orillas del mar',
    director: 'Bladimir Abud',
    type: 'Drama',
    note: 'Drama dominicano.',
  },
  {
    year: 2016,
    title: 'La familia Reyna',
    director: 'Tito Rodríguez',
    type: 'Drama',
    note: 'Drama familiar dominicano.',
  },
  {
    year: 2016,
    title: 'Loki 7',
    director: 'Ernesto Alemany',
    type: 'Comedia',
    note: 'Comedia dominicana.',
  },
  {
    year: 2016,
    title: 'Tubérculo presidente',
    director: 'Archie Lopez',
    type: 'Comedia',
    note: 'Comedia popular dominicana.',
  },
  {
    year: 2016,
    title: 'Caribbean Fantasy',
    director: 'Johanne Gómez Terrero',
    type: 'Documental',
    note: 'Documental dominicano.',
  },
  {
    year: 2017,
    title: 'Carpinteros',
    director: 'José María Cabral',
    type: 'Drama',
    photo:
      'https://media.themoviedb.org/t/p/w780/pDo7m4L0pUSQcSRSGkVc4yOkhsH.jpg',
    note: 'Drama carcelario dominicano seleccionado en Sundance.',
  },
  {
    year: 2017,
    title: 'Colao',
    director: 'Frank Perozo',
    type: 'Comedia romántica',
    note: 'Comedia romántica dominicana.',
  },
  {
    year: 2017,
    title: 'Cocote',
    director: 'Nelson Carlo de Los Santos Arias',
    type: 'Drama',
    note: 'Drama dominicano de amplia circulación internacional.',
  },
  {
    year: 2017,
    title: 'El peor comediante del mundo',
    director: 'Luis Corporán',
    type: 'Comedia / drama',
    note: 'Comedia dramática dominicana.',
  },
  {
    year: 2017,
    title: 'Todas las mujeres son iguales',
    director: 'David Maler',
    type: 'Comedia',
    note: 'Comedia dominicana.',
  },
  {
    year: 2017,
    title: 'Y... a Dios que me perdone!',
    director: 'Ángel Muñiz',
    type: 'Drama',
    note: 'Drama sobre corrupción institucional.',
  },
  {
    year: 2017,
    title: 'Samba',
    director: 'Laura Amelia Guzman e Israel Cardenas',
    type: 'Drama',
    note: 'Drama deportivo dominicano.',
  },
  {
    year: 2017,
    title: 'Luis',
    director: 'Archie Lopez',
    type: 'Drama',
    note: 'Drama dominicano.',
  },
  {
    year: 2017,
    title: 'Azul magia',
    director: 'Yoel Morales',
    type: 'Fantasía / aventura',
    note: 'Fantasía familiar dominicana.',
  },
  {
    year: 2017,
    title: 'Mañana no te olvides',
    director: 'José Enrique Pintor',
    type: 'Drama / comedia',
    note: 'Drama con Freddy Ginebra.',
  },
  {
    year: 2017,
    title: 'Super Papa',
    director: 'Roberto Ángel Salcedo',
    type: 'Comedia',
    note: 'Comedia familiar dominicana.',
  },
  {
    year: 2017,
    title: 'Melocotones',
    director: 'Héctor Valdez',
    type: 'Ciencia ficción',
    note: 'Ciencia ficción dominicana.',
  },
  {
    year: 2018,
    title: 'Trabajo sucio',
    director: 'David Pagán Mariñez',
    type: 'Comedia',
    note: 'Comedia dominicana.',
  },
  {
    year: 2018,
    title: 'Veneno: Primera caída - El relámpago de Jack',
    director: 'Tabaré Blanchard',
    type: 'Biopic / drama',
    note: 'Biografía dramática sobre Jack Veneno.',
  },
  {
    year: 2018,
    title: 'El fantasma de mi novia',
    director: 'Francis Disla',
    type: 'Fantasía romántica',
    note: 'Comedia romántica fantástica.',
  },
  {
    year: 2018,
    title: 'La tragedia de Rio Verde',
    director: 'Miguel Vásquez',
    type: 'Biografía / drama',
    note: 'Sobre el accidente aéreo del equipo de béisbol de Santiago.',
  },
  {
    year: 2018,
    title: 'En altamar',
    director: 'Alfonso Rodríguez',
    type: 'Drama / thriller',
    note: 'Thriller dominicano.',
  },
  {
    year: 2018,
    title: 'Hermaños',
    director: 'Archie Lopez',
    type: 'Drama',
    note: 'Drama dominicano.',
  },
  {
    year: 2018,
    title: 'Juanita',
    director: 'Leticia Tonos',
    type: 'Drama',
    note: 'Drama dominicano.',
  },
  {
    year: 2018,
    title: 'Qué León',
    director: 'Frank Perozo',
    type: 'Comedia romántica',
    note: 'Comedia romántica dominicana.',
  },
  {
    year: 2018,
    title: 'Lo que siento por ti',
    director: 'Raúl Camilo',
    type: 'Drama',
    note: 'Drama coral dominicano.',
  },
  {
    year: 2019,
    title: 'La Fiera y la fiesta',
    director: 'Laura Amelia Guzman e Israel Cardenas',
    type: 'Drama',
    note: 'Drama dominicano con Geraldine Chaplin y Udo Kier.',
  },
  {
    year: 2019,
    title: 'El proyeccionista',
    director: 'José María Cabral',
    type: 'Drama',
    note: 'Drama sobre memoria y cine.',
  },
  {
    year: 2019,
    title: 'La musiquita por dentro',
    director: 'Ernesto Alemany',
    type: 'Comedia',
    note: 'Comedia dominicana.',
  },
  {
    year: 2019,
    title: 'Sol y luna: Dos mejor que una',
    director: 'José Enrique Pintor',
    type: 'Drama romántico',
    note: 'Drama romántico dominicano.',
  },
  {
    year: 2019,
    title: 'Cinderelo',
    director: 'Beto Gómez',
    type: 'Comedia',
    note: 'Comedia dominicana.',
  },
  {
    year: 2019,
    title: 'Kanibaru',
    director: 'Alfonso Rodríguez y Giancarlo Beras-Goico',
    type: 'Drama',
    note: 'Drama dominicano.',
  },
  {
    year: 2019,
    title: 'Casi fiel',
    director: 'Roberto Ángel Salcedo',
    type: 'Comedia',
    note: 'Comedia dominicana.',
  },
  {
    year: 2019,
    title: 'Los Leones',
    director: 'Frank Perozo',
    type: 'Comedia',
    note: 'Secuela de Qué León.',
  },
  {
    year: 2019,
    title: 'Miriam miente',
    director: 'Natalia Cabral y Oriol Estrada',
    type: 'Drama',
    note: 'Drama social dominicano.',
  },
  {
    year: 2019,
    title: 'La isla rota',
    director: 'Félix Germán',
    type: 'Drama histórico',
    note: 'Sobre la masacre del Perejil de 1937.',
  },
  {
    year: 2019,
    title: 'Heroes de Junio: La Historia Prohibida',
    director: 'Roddy Pérez',
    type: 'Drama histórico',
    note: 'Sobre la expedicion de junio de 1959.',
  },
  {
    year: 2019,
    title: 'Isla de plástico',
    director: 'José María Cabral',
    type: 'Documental',
    note: 'Sobre residuos plásticos en República Dominicana.',
  },
  {
    year: 2020,
    title: 'Papi',
    director: 'Noelia Quintero',
    type: 'Drama',
    note: 'Drama dominicano.',
  },
  {
    year: 2020,
    title: 'Mis 500 Locos',
    director: 'Leticia Tonos',
    type: 'Drama histórico',
    note: 'Sobre un médico psiquiatra durante la dictadura de Trujillo.',
  },
  {
    year: 2021,
    title: 'Bantu Mama',
    director: 'Iván Herrera',
    type: 'Drama',
    note: 'Drama dominicano estrenado en SXSW.',
  },
  {
    year: 2021,
    title: 'No es lo que parece',
    director: 'David Maler',
    type: 'Comedia romántica',
    note: 'Comedia romántica dominicana.',
  },
  {
    year: 2021,
    title: 'Candela',
    director: 'Andrés Farías',
    type: 'Drama / thriller',
    note: 'Thriller dominicano.',
  },
  {
    year: 2021,
    title: 'Liborio',
    director: 'Nino Martínez Sosa',
    type: 'Drama',
    note: 'Drama sobre la figura de Liborio Mateo.',
  },
  {
    year: 2021,
    title: 'La Rasante',
    director: 'Hans Garcia',
    type: 'Drama',
    note: 'Drama dominicano.',
  },
  {
    year: 2021,
    title: 'Hotel Coppelia',
    director: 'José María Cabral',
    type: 'Drama histórico',
    note: 'Ambientada durante la Guerra de Abril de 1965.',
  },
  {
    year: 2022,
    title: 'Jupia',
    director: 'José Gómez de Vargas y Julietta Rodríguez',
    type: 'Fantasía oscura / terror',
    note: 'Terror fantástico dominicano.',
  },
  {
    year: 2022,
    title: 'El App',
    director: 'Taba Blanchard',
    type: 'Thriller',
    note: 'Thriller dominicano.',
  },
  {
    year: 2022,
    title: 'Parsley',
    director: 'José María Cabral',
    type: 'Drama histórico',
    note: 'Sobre la masacre del Perejil de 1937.',
  },
  {
    year: 2023,
    title: 'Colao 2',
    director: 'Frank Perozo',
    type: 'Comedia',
    note: 'Secuela de Colao.',
  },
  {
    year: 2023,
    title: 'Cuarencena',
    director: 'David Maler',
    type: 'Comedia / drama',
    note: 'Comedia dramática dominicana.',
  },
  {
    year: 2023,
    title: 'La estrategia del mero',
    director: 'Edgar Alberto De Luque Jácome',
    type: 'Drama',
    note: 'Nominada en Tallinn Black Nights Film Festival.',
  },
  {
    year: 2023,
    title: 'La ternura',
    director: 'Vicente Villanueva',
    type: 'Fantasía / comedia',
    note: 'Coproducción hispano-dominicana.',
  },
  {
    year: 2023,
    title: 'El método',
    director: 'David Maler',
    type: 'Comedia / drama / thriller',
    note: 'Ganadora en el Fine Arts Film Festival.',
  },
  {
    year: 2023,
    title: 'El año del tigre',
    director: 'Yasser Michelén',
    type: 'Comedia',
    note: 'Producida por Bou Group.',
  },
  {
    year: 2024,
    title: 'Aire: Just Breathe',
    director: 'Leticia Tonos',
    type: 'Ciencia ficción / drama',
    note: 'Drama postapocalíptico dominicano.',
  },
]

function slugify(value) {
  return value
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '')
}

export function decadeLabel(year) {
  if (year < 1970) {
    return 'Pioneras'
  }

  return `${Math.floor(year / 10) * 10}s`
}

function getOriginGroup(title) {
  if (outsideScopeTitles.has(title)) {
    return 'outsideScope'
  }

  if (foreignInDominicanRepublicTitles.has(title)) {
    return 'foreignInDr'
  }

  return 'dominicanMade'
}

export const filmCatalog = rawFilms.map((film, index) => {
  const id = `${film.year}-${slugify(film.title)}`
  const originGroup = getOriginGroup(film.title)
  const photo = posterOverrides[id] ?? film.photo ?? null

  return {
    ...film,
    id,
    accent: accents[index % accents.length],
    decade: decadeLabel(film.year),
    originGroup,
    originLabel: originLabels[originGroup],
    photo,
    hasRealPoster: Boolean(photo),
  }
})

export const dominicanFilms = filmCatalog.filter(
  (film) => film.originGroup === 'dominicanMade',
)

export const foreignFilmsInDominicanRepublic = filmCatalog.filter(
  (film) => film.originGroup === 'foreignInDr',
)
